spring:
  datasource:
    url: jdbc:mysql://myihgdemodb.caknqpjqgv7b.ap-southeast-1.rds.amazonaws.com:3306/ihgdemo?useSSL=false
    username: ihguser
    password: ihgpassword
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
       
server:
  port: 8300
